IOC implementation
Valgri/Dependencies-Injection pull request #1
Opened 2024-04-03 07:46 UTC by Valgri

2024-04-03 18:09 UTC, Nazar-bnm requested changes

2024-04-03 18:09 UTC, Nazar-bnm commented on src/index.ts
> +  const usersService = createIoCContainer(config).resolve('Users');
you shouldn't create a new ioc container each time, please create it once and reuse

2024-04-03 18:09 UTC, Nazar-bnm commented on src/ioc/index.ts
> +  ioc.register('Users', new Users(config));
you shouldn't pass the config by yourself it should be injected automatically. This course about dependency injection 🙂
You can find an example of how to automate dependency injection here - https://www.npmjs.com/package/ioc-lite

2024-04-04 08:23 UTC, Valgri commented on src/index.ts
> +  const usersService = createIoCContainer(config).resolve('Users');
thanks! Please check 2nd commit, where I have made changes.

2024-04-04 08:23 UTC, Valgri commented on src/ioc/index.ts
> +  ioc.register('Users', new Users(config));
Got it! Please check 2nd commit, where I have made changes.

2024-04-05 08:48 UTC, Nazar-bnm approved these changes

2024-04-05 08:57 UTC, merged